language: node_js

node_js:
- 6
- 8
- 9

notifications:
  email: false

before_script:
  - npm install --global snyk
  - snyk auth ${SNYK_TOKEN}

script:
  - npm run test
  - snyk test

after_success:
- npm run coverage
- cat ./coverage/lcov.info | node_modules/.bin/coveralls
